# Generated by Django 3.0.5 on 2020-06-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('shortDescription', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('condition', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado')], max_length=10)),
                ('category', models.CharField(choices=[('romance', 'romance'), ('ficcao', 'ficcao'), ('autoajuda', 'autoajuda'), ('didatico', 'didatico')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
